### ISSUE TITLE
hifi_gan-vctk_small vs hifi_gan-vctk_medium (release 2021-03-28)

### ISSUE THREAD

**Issue by svenha** [rhasspy/larynx#10]
The naming confuses me a little bit. hifi_gan-vctk_small is larger (and slower) than hifi_gan-vctk_medium.

**Comment by synesthesiam** [comment]
I wondered this as well, but the labeling from the pre-trained models in the [original repo](https://github.com/jik876/hifi-gan) has the "medium" one as vctk_v2 and "small" as vctk_v3. Based on my understanding of the config files, v2 should be larger/slower than v3.

To make it extra confusing, the small/v3 model uses a different "resblock" but more upscale channels than medium/v2, which uses a similar configuration to the universal_large/v1 model.

I may just flip the medium/small labels though if there is an obvious performance difference between the two. I've focused all my testing on the large vs. small to date.

**Comment by fquirin** [comment]
So I've tested medium and small for a larger number of voices, short and long sentences and `small` was either equal or even slower (within the error bars I guess).

**Comment by synesthesiam** [comment]
I ended up swapping the medium/low vocoder labels in v0.5
