### ISSUE TITLE
Release v0.4.0 contains only a single German larynx-tts-voice (Thorsten)

### ISSUE THREAD

**Issue by eqikkwkp25-cyber** [rhasspy/larynx#16]
All others seem to miss the the onnx model:

larynx-tts-voice-de-de-eva-k-glow-tts_0.4.0_all.deb
383 KB
larynx-tts-voice-de-de-karlsson-glow-tts_0.4.0_all.deb
387 KB
larynx-tts-voice-de-de-pavoque-glow-tts_0.4.0_all.deb
393 KB
larynx-tts-voice-de-de-rebecca-braunert-plunkett-glow-tts_0.4.0_all.deb
367 KB
larynx-tts-voice-de-de-thorsten-glow-tts_0.4.0_all.deb
102 MB

**Comment by synesthesiam** [comment]
Finally got this fixed!

**Comment by eqikkwkp25-cyber** [comment]
Thank you.
