### ISSUE TITLE
Siwis : wrong phonemes for "de"

### ISSUE THREAD

**Issue by ddavout** [rhasspy/larynx#17]
DEBUG:larynx:Words for 'de fait': ['de', 'fait']
DEBUG:larynx:Phonemes for 'de fait': ['#', 'd', 'a', 'm', '#', 'f', 'ɛ', '#', '‖', '‖']

**Comment by synesthesiam** [comment]
This was corrected in a later version of [gruut](https://github.com/rhasspy/gruut). For some bizarre reason, the lexicon had that pronunciation for "de" as the top one!

I will confirm that this is fixed in the Docker image.
