### ISSUE TITLE
Siwis avec + sa wrong phonemes

### ISSUE THREAD

**Issue by ddavout** [rhasspy/larynx#20]
example
DEBUG:gruut.phonemize:Loading lexicon from /usr/lib/larynx-tts/gruut/fr-fr/lexicon.db
DEBUG:larynx:Words for 'avec sa mauvaise vue': ['avec', 'sa', 'mauvaise', 'vue']
DEBUG:larynx:Phonemes for 'avec sa mauvaise vue': ['#', 'a', 'v', 'ɛ', 'k', '#', 'ɛ', 's', 'a', '#', 'm', 'ɔ', 'v', 'ɛ', 'z', '#', 'v', 'y', '#', '‖', '‖']

there should not be a  'ɛ', before  's', 'a'

**Comment by synesthesiam** [comment]
Thanks! I'll have this fixed in the next version (1.2).
