### ISSUE TITLE
Available benchmarks? 

### ISSUE THREAD

**Issue by evanlaf** [rhasspy/larynx#22]
*Not an issue* 

I am looking at using Larynx in my rhasspy implementation and was wondering about Benchmarks before I go ahead and run some tests myself. I am interested in using a select one or two voices at medium quality, and wanted to pick the one with the quickest synthesizing. Just by randomly testing a couple of voices, I see noticeable differences between the voice for the same options and piece of text, so there are differences. But, has anyone put together some benchmarks to compare the voices? 

Also, on a related note, are there any benchmarks in installation methods? My current method of installation is the Docker container then calling a GET request, converting the binary response to a .wav file, and playing the wave file (all in Python 3 on a raspberry pi 4, 64 bit). But, has anyone noticed differences in speed between the Docker vs. Debian vs. Python 3 installation?

**Comment by synesthesiam** [comment]
Benchmarks are now available [in the README](https://github.com/rhasspy/larynx#benchmarks). I ran them all with a local Python installation, so I don't know if Docker/Debian installs will make any difference.
