### ISSUE TITLE
About the use of this software

### ISSUE THREAD

**Issue by Zengyf-CVer** [rhasspy/larynx#23]
@synesthesiam 

Hi,I have contacted this software for the first time. I have cloned it locally now. How do I use it?
I didn't understand the README file, it only wrote the usage method, but didn't write very detailed information on how to deploy and use it.
I want to use it in Python, how do I deploy it? What are the specific steps?

**Comment by synesthesiam** [comment]
I've updated the README with much more installation info now :+1:
