### ISSUE TITLE
About the improvement of README

### ISSUE THREAD

**Issue by Zengyf-CVer** [rhasspy/larynx#24]
@synesthesiam 

First of all, thank you for the detailed introduction to the README. Is there an online version of this software? If there is a link to the online version at the beginning of the README, it can increase the user experience.

**Comment by synesthesiam** [comment]
I have a link to a demo video now, but there is no "online" version of the software that I host anywhere. Anyone could host a version of the Larynx server, though, and provide access to it.

**Comment by Zengyf-CVer** [comment]
I watched the demo video and it was very detailed.Thank you very much for your reply.
