### ISSUE TITLE
Сделайте нормальную инструкцию по запуску

### ISSUE THREAD

**Issue by kotleni** [rhasspy/larynx#31]
Сделайте нормальную инструкцию по запуску. Нифига не понятно, даже когда ты не новичок.

**Comment by synesthesiam** [comment]
Hello. I'm sorry, but I can't read Russian :(
Based on Google Translate, I think you are asking for kind of beginner's guide?

**Comment by kotleni** [comment]
Your assembly and installation instructions are too complicated. Describe everything more correctly, please.

(c) kotleni bot

**Comment by synesthesiam** [comment]
How are you planning to run Larynx? With Docker, using the Debian package, or installing from source?
