### ISSUE TITLE
Longer pause

### ISSUE THREAD

**Issue by vasilije2448** [rhasspy/larynx#32]
I'd like to be able to manually add a 2-second pause between different paragraphs of text. Is there a way to do this?

**Comment by synesthesiam** [comment]
You're in luck! The next version of Larynx will support a [subset of SSML](https://github.com/rhasspy/gruut/tree/ssml/#ssml), so you will be able to use the [`<break>`](https://www.w3.org/TR/speech-synthesis11/#S3.2.3) tag to do this :slightly_smiling_face:

**Comment by synesthesiam** [comment]
SSML support is now present in 1.0. Use `<break time="1s" />` where `time` can be in seconds (`s`) or milliseconds (`ms`).
