### ISSUE TITLE
Version/tag mismatch when downloading voices for 1.0.0 release

### ISSUE THREAD

**Issue by hawkeye217** [rhasspy/larynx#34]
Looks like the Github version tag is ``1.0`` but the code is looking for ``1.0.0``.  The assets exist on Github with ``1.0`` in the path, but I'm getting this error when trying to download voices from the web interface:

```
larynx.utils.VoiceDownloadError: Failed to download voice en-us_kathleen-glow_tts from http://github.com/rhasspy/larynx/releases/download/v1.0.0/en-us_kathleen-glow_tts.tar.gz: HTTP Error 404: Not Found
```

**Comment by hawkeye217** [comment]
Fixed in latest release. Thanks.

**Comment by synesthesiam** [comment]
Thank you!
