### ISSUE TITLE
German voice

### ISSUE THREAD

**Issue by alt131** [rhasspy/larynx#4]
Did you think about using pavoque-data for German voice?
https://github.com/marytts/pavoque-data/releases/tag/v0.2
It has  better quality in comparing with thorsten audio dataset.
It has restriction for commercial using but as I see you already have a voice with that restriction.

**Comment by synesthesiam** [comment]
I did train a voice with it, actually :slightly_smiling_face: 

It didn't sound very good, and I now know that I need to do a forced alignment. I just finished training a German Kaldi model this past weekend with the same IPA phonemes, so I will be aligning and training this voice this week :+1:

**Comment by alt131** [comment]
If you already tried it you can close this issue because I didn't have the hardware to train the model by myself and check it in practice.

**Comment by synesthesiam** [comment]
I'll keep the issue open for now, since I'll be training it soon. Do you know of any good TTS datasets? Or are you interested in contributing your voice?

**Comment by alt131** [comment]
I'm afraid I say no in both cases but if I find TTS datasets with good quality I will let you know.

**Comment by synesthesiam** [comment]
I successfully trained this and three other German voices :slightly_smiling_face: 

https://rhasspy.github.io/larynx/#de-de
