### ISSUE TITLE
New languages need a link

### ISSUE THREAD

**Issue by svenha** [rhasspy/larynx#8]
Thanks @synesthesiam for this excellent tool.

I followed the 'Python installation' method (on Ubuntu 20.10) and added the language `de-de` via `python3 -m gruut de-de download
`. Before I could use the new language, I had to add a link in ~/.local/lib/python3.8/site-packages/gruut/data/ to ~/.config/gruut/de-de; otherwise the new language was not found.

**Comment by alt131** [comment]
I usually copy a new data to /.local/lib/python3.8/site-packages/gruut/data/ after download but yes, I have the same bug too.

**Comment by synesthesiam** [comment]
You're welcome! This should be fixed if you update your version of `gruut` to 0.9.4.

**Comment by svenha** [comment]
Thanks. Now I can work without the link.
